version: "3.7"
services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: bbq
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - bbq-postgres:/var/lib/postgresql/data
  bbq:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - ./rails:/opt/app
    links:
      - postgres
    ports:
      - '8010:8010'
    env_file:
      - .env
volumes:
  bbq-postgres:
