default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bbq_dev
  username: vab3
  password: postgres

test:
  <<: *default
  database: bbq_test
  username: vab3
  password: postgres

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL")

